### ISSUE TITLE
QoL improvements [0.2.3-rolling1]

### ISSUE THREAD

**Issue by BurningInfern0** [Progressbar-Discord-Server/ProgressCLI95#53]
there's a lot of gunk and stuff in the player.py app
would be better to optimize it down

- [x] shrink system variables into a single array for easy use
- [x] fix variables in player.py to use the array instead of variables
- [x] remove anything that deals with score because i don't even understand it
- [x] adapt boot.py into using this new system
- [x] merged green segment spawn with other segments because it honestly is kinda weird
- [x] removed systemLevel and the calculator as it's practically useless
- [x] created a new function called onNewGame() that resets the systemlevel and badge.
- [x] renamed startGame() to loadGame()
- [x] quality controlling my terrible decisions

system, systemlevel, systempro, systembadge, systemlogo, systemunlock, systemunlocklevel
are now packed into an array

pull request - #54
complete

**Comment by BurningInfern0** [comment]
improvements complete, closing issue

**Comment by RealMCoded** [comment]
deterioration incomplete, opening solution

**Comment by BurningInfern0** [comment]
you think you're funny? you think you're real funny, huh? you think you're a real jokester? how about you laugh at this:

message from john github:
you've bneen banned from github, sorry lol no takesie backsies
kind regards,
johnathan github

**Comment by RealMCoded** [comment]
no 😎

**Comment by poggers16** [comment]
how about you ban deez nuts instead

**Comment by poggers16** [comment]
you think i'm unfunny? you think i'm fake unfunny, huh? you think i'm a fake jokester? how not about you cry at this:

rumor from john github:
you've been banned from github, i'm not sorry lol yes takesie backsies
mean regards,
johnathan github

**Comment by BurningInfern0** [comment]
![what](https://user-images.githubusercontent.com/74492478/178093018-049be353-9d3e-4095-afc9-247b00fc4252.png)
